server:
  port: 10010

#配置注册中心2的名称
spring:
  application:
    name: EurekaServer2

eureka:
  client:
    service-url:
      #配置访问的路径
      defaultZone: http://127.0.0.1:10086/eureka
      #允许注册中心自己注册自己
      #register-with-eureka: true