server:
  port: 9090

spring:
  application:
    #不要用下划线
    name: web-consumer
  mvc:
    #静态资源的访问
    static-path-pattern: /static/**
  thymeleaf:
    #不使用页面缓存
    cache: false
    #访问thymeleaf模板页面的路径前缀
    prefix: classpath:/templates/
    #访问thymeleaf模板页面的路径后缀
    suffix: .html
    #使用的文件类型
    mode: HTML5
    #文件的字符编码
    encoding: UTF-8
    servlet:
      #文件的内容类型
      content-type: text/html


eureka:
  #客户端
  client:
    service-url:
      #注册到注册中心的路径（功能模块可以同时注册到多个注册中心，至少要注册一个）
      defaultZone: http://127.0.0.1:10086/eureka