server:
  #前台首页模块服务端口
  port: 8084

spring:
  #后台管理模块的名字
  application:
    name: hbuy_register
  mvc:
    #静态资源的访问
    static-path-pattern: /static/**
  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hbuy?useSSL=false&characterEncoding=utf8
    username: root
    password: root
    # 连接池的配置信息
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
  #thymeleaf模板
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

#配置pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#配置mybatis
mybatis:
  #配置实体封装类别名
  #type-aliases-package: com.java.web.model
  configuration:
    #在控制台中输出mybatis相关日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启MyBatis的二级缓存
    #cache-enabled: true
    #开启懒加载
    lazy-loading-enabled: true
    #false 为按需加载
    aggressive-lazy-loading: false
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      #配置注册的路径
      defaultZone: http://127.0.0.1:10086/eureka
redis:
#使用的redis的库
  database: 0
#访问的ip
  host: 127.0.0.1
#访问端口
  port: 6379
#链接时间
  timeout: 3000



